name: Prebuild Devcontainer

on:
    # This workflow runs on pushes to the main branch and pull requests.
    push:
        branches:
            - main
    pull_request:

permissions:
  packages: write

jobs:
    prebuild-devcontainer:
        runs-on: ubuntu-latest

        steps:

            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Set Docker buildx up for container build
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            # Log into GitHub Container Registry (GHCR) to store the image
            - name: Log into GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor || 'petersellars' }}
                password: ${{ secrets.GITHUB_TOKEN }}
                
            # Per-build the container image
            - name: Pre-build the container image
              uses: devcontainers/ci@v0.3
              with:
                imageName: ghcr.io/catosplace-devcontainers/engineering-base
                cacheFrom: ghcr.io/catosplace-devcontainers/engineering-base
                push: always
          