name: Prebuild Devcontainer

on:
    # This workflow runs on pushes to the main branch and pull requests
    # when the .devcontainer folder is modified or the .dockerignore file
    # is modified.
    push:
        branches:
            - main
        paths:
            - .devcontainer/**
            - .dockerignore
            - .github/workflows/prebuild.yml

    pull_request:
        paths:
            - .devcontainer/**
            - .dockerignore
            - .github/workflows/prebuild.yml

permissions:
  packages: write

jobs:
    prebuild-devcontainer:
        runs-on: ubuntu-24.04

        steps:

            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            # Set Docker buildx up for container build
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

            # Log into GitHub Container Registry (GHCR) to store the image
            - name: Log into GitHub Container Registry
              uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
              with:
                registry: ghcr.io
                username: ${{ github.actor || 'petersellars' }}
                password: ${{ secrets.GITHUB_TOKEN }}
                
            # Pre-build the container image
            - name: Pre-build the container image
              uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
              with:
                imageName: ghcr.io/catosplace-devcontainers/engineering-base
                cacheFrom: ghcr.io/catosplace-devcontainers/engineering-base
                push: always
          